redis:
  image: redis
  volumes:
  - .:/data
  container_name: redis
frontend:
  image: thinkst/canarytokens_frontend
  links:
   - redis
  env_file:
   - frontend.env
  container_name: frontend
  command: twistd -noy frontend.tac
switchboard:
  image: thinkst/canarytokens_switchboard
  ports:
   - "53:53"
   - "53:53/udp"
   - "25:25"
  links:
   - redis
  env_file:
   - switchboard.env
  container_name: switchboard
  command: twistd -noy switchboard.tac
nginx:
  image: thinkst/canarytokens_nginx
  ports:
   - "80:80"
  links:
   - frontend
   - switchboard
  container_name: nginx
  command: /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
